name: Deploy-Web

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@main
    - name: Clean Dependencies
      run: flutter clean
    - name: Install Dependencies
      run: flutter pub get
    - name: Build Web Release
      run: flutter build web --base-href /badge-gen-website/ --release
    - name: Deploy
      run: make deploy-web